name: Java CI with Maven

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # v4 e mai stabil; sau v5 dacă vrei nou

      - name: Set up JDK 17
        uses: actions/setup-java@v4  # Sau @v5 pentru update
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven 
          cache-dependency-path: pom.xml  

      - name: Build and test
        run: mvn --batch-mode --update-snapshots verify

      - name: Prepare artifacts
        run: mkdir staging && cp target/*.jar staging || echo "No JARs found"

      - name: Upload JARs
        uses: actions/upload-artifact@v4
        with:
          name: java-package
          path: staging
